services:
  qdrant: 
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    networks:
      net1:

  rag:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag:latest
    container_name: rag
    ports:
      - "8000:8000"
    networks:
      net1:
    volumes:
      - ./example_docs:/app/example_docs
    environment:
      - GROQ_API_KEY=YOUR_API_KEY_HERE
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.254.254